# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                         PLAYBOOK FOR BOM PROCESSING                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) NFS: Make Local Shares available via NFS Exports
#   02) Process BOM (Download and Extract)
#

- hosts:          "{{ sap_sid|upper }}_SCS"

  name:           BOM Processing
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - set_fact:
      tier:     preparation
    tags:
      - always

  - include_role:
      name:     roles-sap-os/sap-mounts

  - include_role:
      name:     roles-sap-os/sap-exports

  - include_role:
      name:     roles-sap/3.3-bom-processing


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
